//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CA220103.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CA220103.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] lezerloveszet {
            get {
                object obj = ResourceManager.GetObject("lezerloveszet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28,95;31,60
        ///Ricsi;26,99;33,00
        ///Pali;27,45;33,10
        ///Pali;27,66;30,05
        ///Gabi;28,00;32,90
        ///Pali;29,95;30,23
        ///Pali;30,05;30,11
        ///Gabi;30,15;30,04
        ///Gabi;20,51;30,70
        ///Pali;28,43;34,77
        ///Gabi;29,90;28,92
        ///Gabi;31,49;30,20
        ///Pali;25,22;34,90
        ///Gabi;34,52;21,90
        ///Pali;31,27;26,42
        ///Pali;28,66;26,01
        ///Ricsi;23,34;24,91
        ///Pali;28,23;35,71
        ///Pali;30,25;25,75
        ///Ricsi;29,32;33,83
        ///Pali;35,12;33,68
        ///Ricsi;24,93;37,44
        ///Pali;28,79;29,40
        ///Gabi;29,90;29,99
        ///Pali;38,73;35,45
        ///Ricsi;24,01;23,22
        ///Pali;33,92;32,42
        ///Gabi;25,79;39,16
        ///Gabi;34, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lovesek {
            get {
                return ResourceManager.GetString("lovesek", resourceCulture);
            }
        }
    }
}
